name: Test And Release

on: [push]

jobs:
  RunUnitTests:
    name: Run Unit tests
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v2
  
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
  
      - name: Install dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
      - name: Test[With MSBuild configuration]
        run: dotnet test --no-restore --verbosity normal -p:CollectCoverage=true -p:Threshold=90 LWS-GatewayTest/LWS-GatewayTest.csproj

  RunIntegrationTest:
    name: Run Integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x']
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test[With MSBuild configuration]
        run: dotnet test --no-restore --verbosity normal -p:CollectCoverage=true -p:Threshold=90 LWS-GatewayIntegrationTest/LWS-GatewayIntegrationTest.csproj
  
  DeployImage:
    name: Deploy image to docker container registry(public)
    needs: [RunUnitTests, RunIntegrationTest]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    steps:
      - uses: actions/checkout@v2

      - name: Get LWS Version
        id: lws
        run: echo ::set-output name=version::$(cat ./LWS_VERSION)
      
      - name: Setting up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      
      - name: Build Image
        run: |
          docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_USERPASSWORD}}
          docker buildx build -f LWS-Gateway/Dockerfile --platform linux/amd64,linux/arm64 -t kangdroid/lws-gateway:${{ steps.lws.outputs.version }} --push .